version: '3.8'
services:
    redirect:
        hostname: redirect
        image: nginx
        restart: unless-stopped
        networks:
            - network1
        ports:
            - "80:80"
        volumes:
            - ./nginx/redirect/conf.d:/etc/nginx/conf.d
            - ./certbot/.data/var:/webroot

    proxy:
        hostname: proxy
        build: ./nginx/proxy/build
        depends_on:
            - guacamole
            - certbot
        restart: unless-stopped
        networks:
            - network1
        ports:
            - "443:443"
        volumes:
            - ./nginx/proxy/conf.d:/etc/nginx/conf.d
            - ./certbot/.data/certs:/certs
        command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"

    certbot:
        build: ./certbot/build
        depends_on:
            - redirect
        restart: unless-stopped
        networks:
            - network1
        volumes:
            - ./certbot/.data/certs:/certificate_pub
            - ./certbot/.data/etc:/etc/letsencrypt
            - ./certbot/.data/var:/var/www/certbot
        environment:
            - CERTBOT_DOMAINS
            - CERTBOT_EMAIL
            - CERTBOT_STAGING
        entrypoint: /scripts/entrypoint.sh

    mysql:
        hostname: mysql
        build: ./mysql/build
        restart: unless-stopped
        networks:
            - network1
        volumes:
            - ./mysql/.data/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_USER
            - MYSQL_ROOT_PASSWORD

    guacd:
        hostname: guacd
        image: guacamole/guacd
        restart: unless-stopped
        networks:
            - network1


    guacamole:
        hostname: guacamole
        build: ./guacamole/build
        depends_on:
            - guacd
            - mysql
        restart: unless-stopped
        networks:
            - network1
        environment:
            - GUACAMOLE_EXTENSION_PRIORITY
            - GUACD_HOSTNAME
            - MYSQL_HOSTNAME
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - OPENID_AUTHORIZATION_ENDPOINT
            - OPENID_JWKS_ENDPOINT
            - OPENID_ISSUER
            - OPENID_CLIENT_ID
            - OPENID_REDIRECT_URI

    files:
        hostname: files
        build: ./files/build
        restart: unless-stopped
        networks:
            - network1
        volumes:
            - ./files/public:/app/public
    
networks:
    network1:

